# These are supported funding model platforms

github: thuongtruong1009
open_collective: ambition-fund
ko_fi: thuongtruong1009
issuehunt: font-end-pro
custom: ['https://github.com/thuongtruong1009', 'https://github.com/font-end-pro', 'https://github.com/LeQuocPhong']
